#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParksDev
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FOXPRODEV")]
	public partial class FOXPRO2linqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAGENCY(AGENCY instance);
    partial void UpdateAGENCY(AGENCY instance);
    partial void DeleteAGENCY(AGENCY instance);
    partial void InsertAGENCCALC(AGENCCALC instance);
    partial void UpdateAGENCCALC(AGENCCALC instance);
    partial void DeleteAGENCCALC(AGENCCALC instance);
    #endregion
		
		public FOXPRO2linqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FOXPRODEVConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FOXPRO2linqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FOXPRO2linqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FOXPRO2linqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FOXPRO2linqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AGENCY> AGENCies
		{
			get
			{
				return this.GetTable<AGENCY>();
			}
		}
		
		public System.Data.Linq.Table<AGENCCALC> AGENCCALCs
		{
			get
			{
				return this.GetTable<AGENCCALC>();
			}
		}
		
		public System.Data.Linq.Table<AGENFUND> AGENFUNDs
		{
			get
			{
				return this.GetTable<AGENFUND>();
			}
		}
		
		public System.Data.Linq.Table<FUNDTYPE> FUNDTYPEs
		{
			get
			{
				return this.GetTable<FUNDTYPE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AGENCIES")]
	public partial class AGENCY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _AGE_CODE;
		
		private string _AGENCY1;
		
		private string _NAME;
		
		private System.Nullable<double> _ATP_CODE;
		
		private System.Nullable<double> _DIS_CODE;
		
		private string _ADR1;
		
		private string _ADR2;
		
		private string _CITY;
		
		private string _ZIP;
		
		private System.Nullable<double> _AMTMTC;
		
		private System.Nullable<double> _AMTDEV;
		
		private System.Nullable<double> _AMTYEG;
		
		private string _LUPD_USER;
		
		private System.Nullable<System.DateTime> _LUPD_DATE;
		
		private string _LUPD_TIME;
		
		private EntitySet<AGENCCALC> _AGENCCALCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAGE_CODEChanging(double value);
    partial void OnAGE_CODEChanged();
    partial void OnAGENCY1Changing(string value);
    partial void OnAGENCY1Changed();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnATP_CODEChanging(System.Nullable<double> value);
    partial void OnATP_CODEChanged();
    partial void OnDIS_CODEChanging(System.Nullable<double> value);
    partial void OnDIS_CODEChanged();
    partial void OnADR1Changing(string value);
    partial void OnADR1Changed();
    partial void OnADR2Changing(string value);
    partial void OnADR2Changed();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnZIPChanging(string value);
    partial void OnZIPChanged();
    partial void OnAMTMTCChanging(System.Nullable<double> value);
    partial void OnAMTMTCChanged();
    partial void OnAMTDEVChanging(System.Nullable<double> value);
    partial void OnAMTDEVChanged();
    partial void OnAMTYEGChanging(System.Nullable<double> value);
    partial void OnAMTYEGChanged();
    partial void OnLUPD_USERChanging(string value);
    partial void OnLUPD_USERChanged();
    partial void OnLUPD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLUPD_DATEChanged();
    partial void OnLUPD_TIMEChanging(string value);
    partial void OnLUPD_TIMEChanged();
    #endregion
		
		public AGENCY()
		{
			this._AGENCCALCs = new EntitySet<AGENCCALC>(new Action<AGENCCALC>(this.attach_AGENCCALCs), new Action<AGENCCALC>(this.detach_AGENCCALCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE_CODE", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double AGE_CODE
		{
			get
			{
				return this._AGE_CODE;
			}
			set
			{
				if ((this._AGE_CODE != value))
				{
					this.OnAGE_CODEChanging(value);
					this.SendPropertyChanging();
					this._AGE_CODE = value;
					this.SendPropertyChanged("AGE_CODE");
					this.OnAGE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AGENCY", Storage="_AGENCY1", DbType="NVarChar(255)")]
		public string AGENCY1
		{
			get
			{
				return this._AGENCY1;
			}
			set
			{
				if ((this._AGENCY1 != value))
				{
					this.OnAGENCY1Changing(value);
					this.SendPropertyChanging();
					this._AGENCY1 = value;
					this.SendPropertyChanged("AGENCY1");
					this.OnAGENCY1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATP_CODE", DbType="Float")]
		public System.Nullable<double> ATP_CODE
		{
			get
			{
				return this._ATP_CODE;
			}
			set
			{
				if ((this._ATP_CODE != value))
				{
					this.OnATP_CODEChanging(value);
					this.SendPropertyChanging();
					this._ATP_CODE = value;
					this.SendPropertyChanged("ATP_CODE");
					this.OnATP_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIS_CODE", DbType="Float")]
		public System.Nullable<double> DIS_CODE
		{
			get
			{
				return this._DIS_CODE;
			}
			set
			{
				if ((this._DIS_CODE != value))
				{
					this.OnDIS_CODEChanging(value);
					this.SendPropertyChanging();
					this._DIS_CODE = value;
					this.SendPropertyChanged("DIS_CODE");
					this.OnDIS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADR1", DbType="NVarChar(255)")]
		public string ADR1
		{
			get
			{
				return this._ADR1;
			}
			set
			{
				if ((this._ADR1 != value))
				{
					this.OnADR1Changing(value);
					this.SendPropertyChanging();
					this._ADR1 = value;
					this.SendPropertyChanged("ADR1");
					this.OnADR1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADR2", DbType="NVarChar(255)")]
		public string ADR2
		{
			get
			{
				return this._ADR2;
			}
			set
			{
				if ((this._ADR2 != value))
				{
					this.OnADR2Changing(value);
					this.SendPropertyChanging();
					this._ADR2 = value;
					this.SendPropertyChanged("ADR2");
					this.OnADR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(255)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="NVarChar(255)")]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this.OnZIPChanging(value);
					this.SendPropertyChanging();
					this._ZIP = value;
					this.SendPropertyChanged("ZIP");
					this.OnZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMTMTC", DbType="Float")]
		public System.Nullable<double> AMTMTC
		{
			get
			{
				return this._AMTMTC;
			}
			set
			{
				if ((this._AMTMTC != value))
				{
					this.OnAMTMTCChanging(value);
					this.SendPropertyChanging();
					this._AMTMTC = value;
					this.SendPropertyChanged("AMTMTC");
					this.OnAMTMTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMTDEV", DbType="Float")]
		public System.Nullable<double> AMTDEV
		{
			get
			{
				return this._AMTDEV;
			}
			set
			{
				if ((this._AMTDEV != value))
				{
					this.OnAMTDEVChanging(value);
					this.SendPropertyChanging();
					this._AMTDEV = value;
					this.SendPropertyChanged("AMTDEV");
					this.OnAMTDEVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMTYEG", DbType="Float")]
		public System.Nullable<double> AMTYEG
		{
			get
			{
				return this._AMTYEG;
			}
			set
			{
				if ((this._AMTYEG != value))
				{
					this.OnAMTYEGChanging(value);
					this.SendPropertyChanging();
					this._AMTYEG = value;
					this.SendPropertyChanged("AMTYEG");
					this.OnAMTYEGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUPD_USER", DbType="NVarChar(255)")]
		public string LUPD_USER
		{
			get
			{
				return this._LUPD_USER;
			}
			set
			{
				if ((this._LUPD_USER != value))
				{
					this.OnLUPD_USERChanging(value);
					this.SendPropertyChanging();
					this._LUPD_USER = value;
					this.SendPropertyChanged("LUPD_USER");
					this.OnLUPD_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUPD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LUPD_DATE
		{
			get
			{
				return this._LUPD_DATE;
			}
			set
			{
				if ((this._LUPD_DATE != value))
				{
					this.OnLUPD_DATEChanging(value);
					this.SendPropertyChanging();
					this._LUPD_DATE = value;
					this.SendPropertyChanged("LUPD_DATE");
					this.OnLUPD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUPD_TIME", DbType="NVarChar(255)")]
		public string LUPD_TIME
		{
			get
			{
				return this._LUPD_TIME;
			}
			set
			{
				if ((this._LUPD_TIME != value))
				{
					this.OnLUPD_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LUPD_TIME = value;
					this.SendPropertyChanged("LUPD_TIME");
					this.OnLUPD_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AGENCY_AGENCCALC", Storage="_AGENCCALCs", ThisKey="AGE_CODE", OtherKey="AGE_CODE")]
		public EntitySet<AGENCCALC> AGENCCALCs
		{
			get
			{
				return this._AGENCCALCs;
			}
			set
			{
				this._AGENCCALCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AGENCCALCs(AGENCCALC entity)
		{
			this.SendPropertyChanging();
			entity.AGENCY = this;
		}
		
		private void detach_AGENCCALCs(AGENCCALC entity)
		{
			this.SendPropertyChanging();
			entity.AGENCY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AGENCCALCS")]
	public partial class AGENCCALC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _ACA_CODE;
		
		private System.Nullable<double> _AGE_CODE;
		
		private System.Nullable<double> _CTP_CODE;
		
		private System.Nullable<double> _NO_PARC;
		
		private System.Nullable<double> _PCT_BAS;
		
		private System.Nullable<double> _FY_EST;
		
		private System.Nullable<double> _FY_FEE;
		
		private string _COMMENTS;
		
		private string _LUPD_USER;
		
		private System.Nullable<System.DateTime> _LUPD_DATE;
		
		private string _LUPD_TIME;
		
		private EntityRef<AGENCY> _AGENCY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnACA_CODEChanging(double value);
    partial void OnACA_CODEChanged();
    partial void OnAGE_CODEChanging(System.Nullable<double> value);
    partial void OnAGE_CODEChanged();
    partial void OnCTP_CODEChanging(System.Nullable<double> value);
    partial void OnCTP_CODEChanged();
    partial void OnNO_PARCChanging(System.Nullable<double> value);
    partial void OnNO_PARCChanged();
    partial void OnPCT_BASChanging(System.Nullable<double> value);
    partial void OnPCT_BASChanged();
    partial void OnFY_ESTChanging(System.Nullable<double> value);
    partial void OnFY_ESTChanged();
    partial void OnFY_FEEChanging(System.Nullable<double> value);
    partial void OnFY_FEEChanged();
    partial void OnCOMMENTSChanging(string value);
    partial void OnCOMMENTSChanged();
    partial void OnLUPD_USERChanging(string value);
    partial void OnLUPD_USERChanged();
    partial void OnLUPD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLUPD_DATEChanged();
    partial void OnLUPD_TIMEChanging(string value);
    partial void OnLUPD_TIMEChanged();
    #endregion
		
		public AGENCCALC()
		{
			this._AGENCY = default(EntityRef<AGENCY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACA_CODE", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double ACA_CODE
		{
			get
			{
				return this._ACA_CODE;
			}
			set
			{
				if ((this._ACA_CODE != value))
				{
					this.OnACA_CODEChanging(value);
					this.SendPropertyChanging();
					this._ACA_CODE = value;
					this.SendPropertyChanged("ACA_CODE");
					this.OnACA_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE_CODE", DbType="Float")]
		public System.Nullable<double> AGE_CODE
		{
			get
			{
				return this._AGE_CODE;
			}
			set
			{
				if ((this._AGE_CODE != value))
				{
					if (this._AGENCY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAGE_CODEChanging(value);
					this.SendPropertyChanging();
					this._AGE_CODE = value;
					this.SendPropertyChanged("AGE_CODE");
					this.OnAGE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTP_CODE", DbType="Float")]
		public System.Nullable<double> CTP_CODE
		{
			get
			{
				return this._CTP_CODE;
			}
			set
			{
				if ((this._CTP_CODE != value))
				{
					this.OnCTP_CODEChanging(value);
					this.SendPropertyChanging();
					this._CTP_CODE = value;
					this.SendPropertyChanged("CTP_CODE");
					this.OnCTP_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_PARC", DbType="Float")]
		public System.Nullable<double> NO_PARC
		{
			get
			{
				return this._NO_PARC;
			}
			set
			{
				if ((this._NO_PARC != value))
				{
					this.OnNO_PARCChanging(value);
					this.SendPropertyChanging();
					this._NO_PARC = value;
					this.SendPropertyChanged("NO_PARC");
					this.OnNO_PARCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCT_BAS", DbType="Float")]
		public System.Nullable<double> PCT_BAS
		{
			get
			{
				return this._PCT_BAS;
			}
			set
			{
				if ((this._PCT_BAS != value))
				{
					this.OnPCT_BASChanging(value);
					this.SendPropertyChanging();
					this._PCT_BAS = value;
					this.SendPropertyChanged("PCT_BAS");
					this.OnPCT_BASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FY_EST", DbType="Float")]
		public System.Nullable<double> FY_EST
		{
			get
			{
				return this._FY_EST;
			}
			set
			{
				if ((this._FY_EST != value))
				{
					this.OnFY_ESTChanging(value);
					this.SendPropertyChanging();
					this._FY_EST = value;
					this.SendPropertyChanged("FY_EST");
					this.OnFY_ESTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FY_FEE", DbType="Float")]
		public System.Nullable<double> FY_FEE
		{
			get
			{
				return this._FY_FEE;
			}
			set
			{
				if ((this._FY_FEE != value))
				{
					this.OnFY_FEEChanging(value);
					this.SendPropertyChanging();
					this._FY_FEE = value;
					this.SendPropertyChanged("FY_FEE");
					this.OnFY_FEEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="NVarChar(255)")]
		public string COMMENTS
		{
			get
			{
				return this._COMMENTS;
			}
			set
			{
				if ((this._COMMENTS != value))
				{
					this.OnCOMMENTSChanging(value);
					this.SendPropertyChanging();
					this._COMMENTS = value;
					this.SendPropertyChanged("COMMENTS");
					this.OnCOMMENTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUPD_USER", DbType="NVarChar(255)")]
		public string LUPD_USER
		{
			get
			{
				return this._LUPD_USER;
			}
			set
			{
				if ((this._LUPD_USER != value))
				{
					this.OnLUPD_USERChanging(value);
					this.SendPropertyChanging();
					this._LUPD_USER = value;
					this.SendPropertyChanged("LUPD_USER");
					this.OnLUPD_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUPD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LUPD_DATE
		{
			get
			{
				return this._LUPD_DATE;
			}
			set
			{
				if ((this._LUPD_DATE != value))
				{
					this.OnLUPD_DATEChanging(value);
					this.SendPropertyChanging();
					this._LUPD_DATE = value;
					this.SendPropertyChanged("LUPD_DATE");
					this.OnLUPD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUPD_TIME", DbType="NVarChar(255)")]
		public string LUPD_TIME
		{
			get
			{
				return this._LUPD_TIME;
			}
			set
			{
				if ((this._LUPD_TIME != value))
				{
					this.OnLUPD_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LUPD_TIME = value;
					this.SendPropertyChanged("LUPD_TIME");
					this.OnLUPD_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AGENCY_AGENCCALC", Storage="_AGENCY", ThisKey="AGE_CODE", OtherKey="AGE_CODE", IsForeignKey=true)]
		public AGENCY AGENCY
		{
			get
			{
				return this._AGENCY.Entity;
			}
			set
			{
				AGENCY previousValue = this._AGENCY.Entity;
				if (((previousValue != value) 
							|| (this._AGENCY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AGENCY.Entity = null;
						previousValue.AGENCCALCs.Remove(this);
					}
					this._AGENCY.Entity = value;
					if ((value != null))
					{
						value.AGENCCALCs.Add(this);
						this._AGE_CODE = value.AGE_CODE;
					}
					else
					{
						this._AGE_CODE = default(Nullable<double>);
					}
					this.SendPropertyChanged("AGENCY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AGENFUNDS")]
	public partial class AGENFUND
	{
		
		private System.Nullable<double> _AGF_CODE;
		
		private System.Nullable<double> _AGE_CODE;
		
		private System.Nullable<double> _FTP_CODE;
		
		private System.Nullable<double> _AMT;
		
		private string _COMMENTS;
		
		private string _LUPD_USER;
		
		private System.Nullable<System.DateTime> _LUPD_DATE;
		
		private string _LUPD_TIME;
		
		public AGENFUND()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGF_CODE", DbType="Float")]
		public System.Nullable<double> AGF_CODE
		{
			get
			{
				return this._AGF_CODE;
			}
			set
			{
				if ((this._AGF_CODE != value))
				{
					this._AGF_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE_CODE", DbType="Float")]
		public System.Nullable<double> AGE_CODE
		{
			get
			{
				return this._AGE_CODE;
			}
			set
			{
				if ((this._AGE_CODE != value))
				{
					this._AGE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTP_CODE", DbType="Float")]
		public System.Nullable<double> FTP_CODE
		{
			get
			{
				return this._FTP_CODE;
			}
			set
			{
				if ((this._FTP_CODE != value))
				{
					this._FTP_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMT", DbType="Float")]
		public System.Nullable<double> AMT
		{
			get
			{
				return this._AMT;
			}
			set
			{
				if ((this._AMT != value))
				{
					this._AMT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="NVarChar(255)")]
		public string COMMENTS
		{
			get
			{
				return this._COMMENTS;
			}
			set
			{
				if ((this._COMMENTS != value))
				{
					this._COMMENTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUPD_USER", DbType="NVarChar(255)")]
		public string LUPD_USER
		{
			get
			{
				return this._LUPD_USER;
			}
			set
			{
				if ((this._LUPD_USER != value))
				{
					this._LUPD_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUPD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LUPD_DATE
		{
			get
			{
				return this._LUPD_DATE;
			}
			set
			{
				if ((this._LUPD_DATE != value))
				{
					this._LUPD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUPD_TIME", DbType="NVarChar(255)")]
		public string LUPD_TIME
		{
			get
			{
				return this._LUPD_TIME;
			}
			set
			{
				if ((this._LUPD_TIME != value))
				{
					this._LUPD_TIME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FUNDTYPES")]
	public partial class FUNDTYPE
	{
		
		private System.Nullable<double> _FTP_CODE;
		
		private string _HEADER;
		
		private string _FUND_TYPE;
		
		private string _FUND_ABRV;
		
		private bool _CALCULATED;
		
		private System.Nullable<double> _FUND_AMT;
		
		public FUNDTYPE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTP_CODE", DbType="Float")]
		public System.Nullable<double> FTP_CODE
		{
			get
			{
				return this._FTP_CODE;
			}
			set
			{
				if ((this._FTP_CODE != value))
				{
					this._FTP_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEADER", DbType="NVarChar(255)")]
		public string HEADER
		{
			get
			{
				return this._HEADER;
			}
			set
			{
				if ((this._HEADER != value))
				{
					this._HEADER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUND_TYPE", DbType="NVarChar(255)")]
		public string FUND_TYPE
		{
			get
			{
				return this._FUND_TYPE;
			}
			set
			{
				if ((this._FUND_TYPE != value))
				{
					this._FUND_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUND_ABRV", DbType="NVarChar(255)")]
		public string FUND_ABRV
		{
			get
			{
				return this._FUND_ABRV;
			}
			set
			{
				if ((this._FUND_ABRV != value))
				{
					this._FUND_ABRV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALCULATED", DbType="Bit NOT NULL")]
		public bool CALCULATED
		{
			get
			{
				return this._CALCULATED;
			}
			set
			{
				if ((this._CALCULATED != value))
				{
					this._CALCULATED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUND_AMT", DbType="Float")]
		public System.Nullable<double> FUND_AMT
		{
			get
			{
				return this._FUND_AMT;
			}
			set
			{
				if ((this._FUND_AMT != value))
				{
					this._FUND_AMT = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
