//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MVC.MS.Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENBALANCFY
    {
        public double ABF_CODE { get; set; }
        public Nullable<double> AGE_CODE { get; set; }
        public Nullable<double> FY { get; set; }
        public Nullable<double> AMT_BEG { get; set; }
        public Nullable<double> AMT_BAS { get; set; }
        public Nullable<double> AMT_TRA { get; set; }
        public Nullable<double> AMT_INT { get; set; }
        public Nullable<double> MTC_EST { get; set; }
        public Nullable<double> YEG_BEG { get; set; }
        public Nullable<double> YEG_TOT { get; set; }
        public Nullable<double> YEG_CAL { get; set; }
        public Nullable<double> YEG_TRA { get; set; }
        public Nullable<double> FEE_BEG { get; set; }
        public Nullable<double> FEE_CAL { get; set; }
        public Nullable<double> FEE_PAY { get; set; }
        public string LUPD_USER { get; set; }
        public Nullable<System.DateTime> LUPD_DATE { get; set; }
        public string LUPD_TIME { get; set; }
    }
}
