//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MVC.MS.Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNDTYPE
    {
        public Nullable<double> FTP_CODE { get; set; }
        public string HEADER { get; set; }
        public string FUND_TYPE { get; set; }
        public string FUND_ABRV { get; set; }
        public bool CALCULATED { get; set; }
        public Nullable<double> FUND_AMT { get; set; }
    }
}
