//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MVC.MS.Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grant
    {
        public string CON { get; set; }
        public string Con2 { get; set; }
        public string GRANT_NUM { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<System.DateTime> Period_from { get; set; }
        public Nullable<System.DateTime> Period_to { get; set; }
        public string locode { get; set; }
        public string supDist { get; set; }
        public string objcode { get; set; }
        public string eo { get; set; }
    }
}
