//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MVC.BB.Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCy
    {
        public double AGE_CODE { get; set; }
        public string AGENCY1 { get; set; }
        public string NAME { get; set; }
        public Nullable<double> ATP_CODE { get; set; }
        public Nullable<double> DIS_CODE { get; set; }
        public string ADR1 { get; set; }
        public string ADR2 { get; set; }
        public string CITY { get; set; }
        public string ZIP { get; set; }
        public Nullable<double> AMTMTC { get; set; }
        public Nullable<double> AMTDEV { get; set; }
        public Nullable<double> AMTYEG { get; set; }
        public string LUPD_USER { get; set; }
        public Nullable<System.DateTime> LUPD_DATE { get; set; }
        public string LUPD_TIME { get; set; }
    }
}
