//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MVC.BB.Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCCALC
    {
        public double ACA_CODE { get; set; }
        public Nullable<double> AGE_CODE { get; set; }
        public Nullable<double> CTP_CODE { get; set; }
        public Nullable<double> NO_PARC { get; set; }
        public Nullable<double> PCT_BAS { get; set; }
        public Nullable<double> FY_EST { get; set; }
        public Nullable<double> FY_FEE { get; set; }
        public string COMMENTS { get; set; }
        public string LUPD_USER { get; set; }
        public Nullable<System.DateTime> LUPD_DATE { get; set; }
        public string LUPD_TIME { get; set; }
    }
}
