//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MVC.BB.Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALTYPE
    {
        public double CTP_CODE { get; set; }
        public string CALC_TYPE { get; set; }
        public Nullable<double> FY_FROM { get; set; }
        public Nullable<double> FY_TO { get; set; }
        public Nullable<double> ANNUALLY { get; set; }
        public Nullable<double> NO_PARC { get; set; }
        public Nullable<double> PRC_BAS { get; set; }
        public Nullable<double> YEAR_FR { get; set; }
        public Nullable<double> MONTH_FR { get; set; }
        public Nullable<double> YEAR_TO { get; set; }
        public Nullable<double> MONTH_TO { get; set; }
    }
}
