//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MVC.BB.Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEREST
    {
        public Nullable<double> INT_CODE { get; set; }
        public Nullable<System.DateTime> ENTERED { get; set; }
        public Nullable<double> YEAR { get; set; }
        public Nullable<double> MONTH { get; set; }
        public Nullable<double> INT { get; set; }
        public string COMMENTS { get; set; }
        public bool DISTRIB { get; set; }
        public string LUPD_USER { get; set; }
        public Nullable<System.DateTime> LUPD_DATE { get; set; }
        public string LUPD_TIME { get; set; }
    }
}
