//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MVC.BB.Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_CARA_TABLE
    {
        public Nullable<long> Cank { get; set; }
        public Nullable<double> AGE_CODE { get; set; }
        public string AGENCY { get; set; }
        public string Full_name { get; set; }
        public string NAME { get; set; }
        public Nullable<double> FY { get; set; }
        public string CALC_TYPE { get; set; }
        public Nullable<double> PCT_BAS { get; set; }
        public Nullable<double> ANNUALLY { get; set; }
        public Nullable<double> YEG_TOT { get; set; }
        public Nullable<double> YEG_TRA_SUM { get; set; }
        public Nullable<double> AMTMTC { get; set; }
        public Nullable<double> MTC_EST { get; set; }
        public Nullable<double> MTC_EST_SUM { get; set; }
        public Nullable<double> YEG_CAL { get; set; }
    }
}
