//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MVC.BB.Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONTYPE
    {
        public Nullable<double> TTP_CODE { get; set; }
        public string TRAN_TYPE { get; set; }
        public bool PLUS_SIGN { get; set; }
    }
}
